// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuI4biWZPU4QPJxCyeHxbOW64wMgnjmD8',
    appId: '1:820181082511:web:6d8751f900536ca8ad2bfa',
    messagingSenderId: '820181082511',
    projectId: 'daangn-demo-3784c',
    authDomain: 'daangn-demo-3784c.firebaseapp.com',
    storageBucket: 'daangn-demo-3784c.appspot.com',
    measurementId: 'G-LZVE1SJEX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKAxVhVyS7nMVJVdLTjjx9Hmu_tVlwPRs',
    appId: '1:820181082511:android:6c36365997545a53ad2bfa',
    messagingSenderId: '820181082511',
    projectId: 'daangn-demo-3784c',
    storageBucket: 'daangn-demo-3784c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOC_SiiTwaukS7164P9XNeBUt8gOyKog',
    appId: '1:820181082511:ios:9c67eb650df0c5abad2bfa',
    messagingSenderId: '820181082511',
    projectId: 'daangn-demo-3784c',
    storageBucket: 'daangn-demo-3784c.appspot.com',
    iosBundleId: 'com.example.karrotapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBOC_SiiTwaukS7164P9XNeBUt8gOyKog',
    appId: '1:820181082511:ios:3bbac68fd622c2d0ad2bfa',
    messagingSenderId: '820181082511',
    projectId: 'daangn-demo-3784c',
    storageBucket: 'daangn-demo-3784c.appspot.com',
    iosBundleId: 'com.example.fastAppBase',
  );
}
